const SYMBOLS={W:{icon:'👻',name:'Phantom Wild',pay:{3:20,4:75,5:250}},S:{icon:'🩸',name:'Blood Scatter',scatter:{3:2,4:10,5:50}},P:{icon:'🧪',name:'Poison Vial',pay:{3:5,4:20,5:75}},G:{icon:'💀',name:'Skull',pay:{3:4,4:15,5:50}},K:{icon:'🗝️',name:'Bone Key',pay:{3:3,4:10,5:35}},L:{icon:'🏮',name:'Lantern',pay:{3:2,4:8,5:25}},B:{icon:'📖',name:'Cursed Book',pay:{3:2,4:6,5:18}},A:{icon:'A',name:'A',pay:{3:1,4:4,5:12}},R:{icon:'K',name:'K',pay:{3:1,4:3,5:10}},Q:{icon:'Q',name:'Q',pay:{3:1,4:3,5:8}}};
const WEIGHTS=['Q','Q','Q','R','R','R','A','A','A','B','B','L','L','K','K','G','G','P','P','S','W'];
const LINES=[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1],[0,1,1,1,0],[2,1,1,1,2],[1,0,1,2,1],[1,2,1,0,1],[0,1,0,1,0],[2,1,2,1,2],[0,2,0,2,0],[2,0,2,0,2],[0,2,2,2,0],[2,0,0,0,2],[1,1,0,1,1]];
const taunts=['The house grows restless…','The spirits remain silent.','The door stays closed.','Your luck fades…','Something is watching.'];
let credits=2000,lineBet=1,lastWin=0,blood=0,poison=0,spinning=false,grid=[];
const $=id=>document.getElementById(id),reels=$('reels'),lineLayer=$('paylineLayer');
function pick(){return WEIGHTS[Math.floor(Math.random()*WEIGHTS.length)]}
function buildGrid(){grid=Array.from({length:3},()=>Array.from({length:5},pick))}
function drawGrid(){reels.innerHTML='';for(let r=0;r<3;r++)for(let c=0;c<5;c++){const d=document.createElement('div');d.className='cell';d.dataset.r=r;d.dataset.c=c;d.textContent=SYMBOLS[grid[r][c]].icon;reels.appendChild(d)}}
function totalBet(){return lineBet*LINES.length}
function render(){ $('credits').textContent=credits;$('lineBet').textContent=lineBet;$('totalBet').textContent=totalBet();$('lastWin').textContent=lastWin;$('bloodMeter').value=blood;$('poisonMeter').value=poison;$('bloodLiquid').style.height=Math.max(8,blood)+'%';$('poisonLiquid').style.height=Math.max(8,poison)+'%';$('spin').disabled=spinning||credits<totalBet()}
function clearWins(){document.querySelectorAll('.cell').forEach(x=>x.classList.remove('win','scatter-win'));lineLayer.innerHTML=''}
function cellAt(r,c){return document.querySelector(`.cell[data-r="${r}"][data-c="${c}"]`)}
function evaluateLine(rows){let base=null,count=0,cells=[];for(let c=0;c<5;c++){const sym=grid[rows[c]][c];if(c===0){if(sym==='S')return null;base=sym==='W'?null:sym;count=1;cells.push([rows[c],c]);continue}if(sym==='S')break;if(base===null&&sym!=='W')base=sym;if(sym==='W'||base===null||sym===base){count++;cells.push([rows[c],c])}else break}if(count<3)return null;const key=base||'W',mult=SYMBOLS[key].pay?.[count]||0;return mult?{key,count,mult,cells}:null}
function linePoints(rows){return rows.map((r,c)=>`${50+c*100},${50+r*100}`).join(' ')}
function evaluate(){clearWins();let total=0,wins=[];LINES.forEach((rows,i)=>{const w=evaluateLine(rows);if(w){w.line=i+1;w.amount=w.mult*lineBet;total+=w.amount;wins.push(w)}});const scat=[];for(let r=0;r<3;r++)for(let c=0;c<5;c++)if(grid[r][c]==='S')scat.push([r,c]);if(scat.length>=3){const n=Math.min(5,scat.length),amt=(SYMBOLS.S.scatter[n]||0)*totalBet();total+=amt;scat.forEach(([r,c])=>cellAt(r,c).classList.add('scatter-win'));blood=Math.min(100,blood+25*n);wins.push({scatter:true,count:n,amount:amt})}wins.forEach(w=>{if(w.scatter)return;w.cells.forEach(([r,c])=>cellAt(r,c).classList.add('win'));const p=document.createElementNS('http://www.w3.org/2000/svg','polyline');p.setAttribute('points',linePoints(LINES[w.line-1]));lineLayer.appendChild(p);if(w.key==='P')poison=Math.min(100,poison+10*w.count);else blood=Math.min(100,blood+4*w.count)});if(poison>=100){const venom=totalBet()*5;total+=venom;poison=0;wins.push({venom:true,amount:venom})}credits+=total;lastWin=total;if(total){const lineWins=wins.filter(w=>w.line).length;$('message').textContent=`${lineWins} line win${lineWins===1?'':'s'}${scat.length>=3?' + Blood Scatter':''}. Total win: ${total} credits.`}else $('message').textContent=taunts[Math.floor(Math.random()*taunts.length)];render()}
async function spin(){if(spinning||credits<totalBet())return;spinning=true;credits-=totalBet();lastWin=0;clearWins();render();$('message').textContent='The spirits turn all twenty lines…';const cells=[...document.querySelectorAll('.cell')];for(let i=0;i<12;i++){cells.forEach(x=>{x.classList.add('spinning');x.textContent=SYMBOLS[pick()].icon});await new Promise(r=>setTimeout(r,45+i*4))}buildGrid();cells.forEach((x,i)=>{const r=Math.floor(i/5),c=i%5;x.textContent=SYMBOLS[grid[r][c]].icon;x.classList.remove('spinning')});spinning=false;setTimeout(evaluate,250)}
function fillInfo(){const box=$('paytable');box.innerHTML='<div class="pay-row"><b>Symbol</b><b>3</b><b>4</b><b>5</b></div>'+Object.entries(SYMBOLS).map(([k,s])=>{if(k==='S')return `<div class="pay-row"><span>${s.icon} ${s.name}</span><span>${s.scatter[3]}× total</span><span>${s.scatter[4]}×</span><span>${s.scatter[5]}×</span></div>`;return `<div class="pay-row"><span>${s.icon} ${s.name}</span><span>${s.pay[3]}×</span><span>${s.pay[4]}×</span><span>${s.pay[5]}× line bet</span></div>`}).join('');$('lineList').innerHTML=LINES.map((r,i)=>`<span>${i+1}: ${r.map(x=>x+1).join('-')}</span>`).join('')}
$('spin').onclick=spin;$('betDown').onclick=()=>{lineBet=Math.max(1,lineBet-1);render()};$('betUp').onclick=()=>{lineBet=Math.min(10,lineBet+1);render()};$('reset').onclick=()=>{credits=2000;lineBet=1;lastWin=0;blood=0;poison=0;buildGrid();drawGrid();clearWins();$('message').textContent='20 lines active. The spirits are listening.';render()};$('info').onclick=()=>{$('infoDialog').showModal()};fillInfo();buildGrid();drawGrid();render();